config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#index'
  get    'about'   => 'welcome#about'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :donuts do
    resources :donut_ratings
  end
  resources :donut_shops
  get 'new_donut_shop_form' => 'donut_shops#new_donut_shop_form'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :donuts, only: [:index, :create, :show, :update, :destroy]
      resources :donut_shops, only: [:index, :create, :show, :update, :destroy]
      resources :donut_ratings, only: [:index, :create, :show, :update, :destroy]
      resources :sessions, only: [:create]
    end
  end

end

app/models/donut.rb
class Donut < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  include ActiveModel::Serialization
  has_many :donut_ratings
  belongs_to :donut_shop
  accepts_nested_attributes_for :donut_shop

  validates :name, :description, :donut_shop_id, :presence => true
  validates :name, uniqueness: { scope: :donut_shop_id } 

end

app/models/donut_rating.rb
class DonutRating < ActiveRecord::Base
  validates :user_id, :donut_id, :score, :description, :donut_shop_id, :presence => true

  def self.average_rating(donut_id)
    ratings = where(donut_id: donut_id)
    sum(ratings) / ratings.length
  end

  private
  def self.sum(ratings)
    ratings.inject (0) {|sum, r| sum + r.score } 
  end
end

app/models/donut_shop.rb
class DonutShop < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  has_many :donut_ratings
  has_many :donuts

  validates :name, :description, :address, :phone, :website, presence: true
  validates :address, :phone, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many  :donut_ratings
  has_many :rated_donuts, through: :donut_ratings, foreign_key: :donut
  has_many :rated_donut_shops, through: :donut_ratings, foreign_key: :donut_shop
  validates :email, :first_name, :last_name, :password, :presence => true
  validates_confirmation_of :password, :message => "They need to match"

   before_create :generate_authentication_token

  private
  def generate_authentication_token
    loop do
      self.authentication_token = SecureRandom.base64(64)
      break unless User.find_by(authentication_token: authentication_token)
    end
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  protect_from_forgery with: :null_session

  before_action :destroy_session
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def destroy_session
    request.session_options[:skip] = true
  end


  def not_found
    return api_error(status: 404, errors: 'Sorry, the record was not found')
  end

 private
  def authenticate_user!
    user_email = params[:email]
    user = user_email && User.find_by(email: user_email)

    if user && ActiveSupport::SecurityUtils.secure_compare(user.authentication_token, params["token"])
      @current_user = user
    else
      return unauthenticated!
    end
  end

   def unauthenticated!
    response.headers['WWW-Authenticate'] = "Token realm=Application"
    render json: { error: 'Bad credentials' }, status: 401
  end
end

app/controllers/api/v1/donuts_controller.rb
class Api::V1::DonutsController < Api::V1::BaseController
  before_filter :authenticate_user!
  def show
    donut = Donut.find(params[:id])
    render(json: Api::V1::DonutSerializer.new(donut).to_json)
  end

   def index
    donuts = Donut.all
    render(json: donuts.each{|d| Api::V1::DonutSerializer.new(d).to_json})
  end
end

app/controllers/api/v1/sessions_controller.rb
class Api::V1::SessionsController < Api::V1::BaseController
  def create
    user = User.find_by(email: create_params[:email])
    if user && user.authenticate(create_params[:password])
      render(
        json: Api::V1::SessionSerializer.new(user, root: false).to_json,
        status: 201
      )
    else
      render json: { error: 'Issue with the email or password' }, status: 401
    end
  end

  private
  def create_params
    params.permit(:email, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donut_ratings_controller.rb
require 'support/spec_test_helper'
class DonutRatingsController < ApplicationController

  def create
    @rating = DonutRating.new(rating_params)
    @rating.donut_id = params[:donut_id]
    @rating.user_id = session[:user_id]
    @donut = Donut.find(@rating.donut_id)
    @rating.donut_shop_id = @donut.donut_shop_id
    if @rating.valid?
      @rating.save
      redirect_to @donut
    else
      @errors = @rating.errors.full_messages
      render 'donut_shops/new'
    end
  end

  private

  def rating_params
    params.require(:donut_rating).permit( :score, :description)
  end


end

app/controllers/donut_shops_controller.rb
class DonutShopsController < ApplicationController


  def index
    @shops = DonutShop.all
  end

  def show
    @shop = DonutShop.find(params[:id])
    @donuts = Donut.find_by(:donut_shop_id => @shop.id)
  end

  def create
    @shop = DonutShop.new(shop_params)
    if @shop.save
      redirect_to @shop
    else
      @errors = @shop.errors.full_messages
      render 'donut_shops/new'
    end
  end

  def new_donut_shop_form
    respond_to do |format|
      format.js 
    end
  end


  private

  def shop_params
    params.require(:donut_shop).permit(:name, :description, :address, :phone, :website, :picture)
  end
  
end

app/controllers/donuts_controller.rb
class DonutsController < ApplicationController

  def new
    @shops = DonutShop.all
  end

  def create
    @donut = Donut.new(donut_params)
    if @donut.save
      render "donuts/show"
    else
      redirect_to root_path
    end
  end

  def show
    session[:donut_id] = params[:id]
    @donut = Donut.find(params[:id])
    @donut_shop = DonutShop.find(@donut.donut_shop_id)
    @ratings = DonutRating.where(donut_id: session[:donut_id]) 
    
  end

  def index
    @donuts = Donut.all
  end

  private

  def donut_params
    params.require(:donut).permit(:name, :description, :occasion, :type_of_donut, :donut_shop_id, :picture)
  end


 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create 
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to login_url, :notice => "Something went wrong, try again."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You are logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def new 
    @user = User.new
  end
  
  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "You signed up!"
    else
      @errors = @user.errors.full_messages
      render "users/new"
    end 
  end

  def show
    @user = User.find(session[:user_id])
    @donuts_rated = DonutRating.where(user_id: session[:user_id])
  end

  def update
    @user = @user = User.find(session[:user_id])
    @user.update(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "You updated your profile."
    else
      @errors = @user.errors.full_messages
      render "users/new"
    end 

  end

  private
  
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/donut_shops_helper.rb
module DonutShopsHelper
  
end

app/helpers/form_helper.rb
module FormHelper
  def setup_donut(donut)
    donut.donut_shop ||= DonutShop.new
    donut
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in
    return true if session[:user_id] != nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/donut_ratings/_new.html.erb
<section class="row col-md-12 new_rating" >
    <div class="span4 well">
      <%= form_for DonutRating.new, :url => donut_donut_ratings_path(@donut),  :html => {:class => "form-horizontal center"}  do |f| %>
        <h3 class ="col-md-10">Rate This Donut</h3>
        <div class="form-group">
          <%= f.label :score, class:"control-label col-sm-4" %>
          <div class="col-sm-6 radio">
            <%= f.collection_radio_buttons(:score, [[1, '1. Didnt finish it'], [2, '2. Finished it but wont eat it again'], [3, '3. It fills the hunger'], [4, '4. is a lovely number'], [5, '5 is a yes']],  :first, :last, :item_wrapper_class => 'btn btn-primary', :default => true) do |b| %>
              <% b.label { b.radio_button + b.text } %>
            <% end %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :occasion, class:"control-label col-sm-4" %>
          <div class="col-sm-6">
            <%= f.text_field :occasion, spellcheck:"true" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :description, class:"control-label col-sm-4" %>
          <div class="col-sm-6">
            <%= f.text_area :description, spellcheck:"true" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-4 col-sm-10">
            <%= f.submit "Rate a Donut", class:"btn btn-default" %>
          </div>
        </div>  
      <% end %>
    </div>
</section>  

app/views/donut_shops/_form.html.erb
<div class="row">
  <div class="span6 well">
    <%= form_for DonutShop.new, :html => {:class => "form-horizontal center"} do |f| %>
        <div class="form-group">
          <%= f.label :name, class:"control-label col-sm-2 col-sm-offset-2" %>
          <div class="col-sm-4">
            <%= f.text_field :name %>
          </div>
        </div>
        <div class="form-group">  
          <%= f.label :description, class:"control-label col-sm-2 col-sm-offset-2" %></br>
          <div class="col-sm-4">
            <%= f.text_area :description, spellcheck: "true" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :address, class:"control-label col-sm-2 col-sm-offset-2" %>
          <div class="col-sm-4"> 
            <%= f.text_field :address %>
         </div>
        </div>
        <div class="form-group"> 
          <%= f.label :phone, class:"control-label col-sm-2 col-sm-offset-2" %>
          <div class="col-sm-4">
            <%= f.text_field :phone %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :website, class:"control-label col-sm-2 col-sm-offset-2" %>
          <div class="col-sm-4">
            <%= f.text_field :website %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :picture, class:"control-label col-sm-2 col-sm-offset-2" %>
          <div class="col-sm-4">
            <%= f.hidden_field(:picture_cache) %>
            <%= f.file_field(:picture) %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= submit_tag "Add a Donut Shop", class:"btn btn-default" %>
          </div>
         </div> 
    <% end %>
    </div>
  </div>

app/views/donut_shops/_map.html.erb
<div ="map"></div>

app/views/donut_shops/index.html.erb
<h2 class="title_page">Donut Shops<h2>
<div class="row top-buffer donut">
  <% @shops.each do |shop| %>
  <section class="col-md-3 col-md-offset-2 top-buffer">
    <div class="donut_shop">
      <h4><%= link_to shop.name, donut_shop_path(shop) %> </h4>
      <h5>Description: <%= shop.description %></h5>
      <h5 id = 'address'>Address: <%= shop.address %></h5>
      <div ="map"></div>
    </div>  
  </section>
<% end %>
</div>

<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <% if logged_in %>
      <%= render  "donut_shops/form" %>
    <% else %>
      <%= render partial: 'users/login_needed' %>
    <% end %>
  </div> 
</div>  

app/views/donut_shops/new.html.erb
<%= render "donut_shops/form" %>

app/views/donut_shops/new_donut_shop_form.js.erb
$('.donut_shop_select').html("<%=j render partial: 'donut_shops/form' %>");

app/views/donut_shops/show.html.erb
<script async defer
      src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['API_KEY']%>&callback=initMap">
</script>
<div class="row">       
  <section class="col-md-8 col-md-offset-2 donut_shop_show">
    <h2>A Donut Shop </h2>
    <p><%= @shop.name%></p>
    <p><%= @shop.description %></p>
    <p id ="address"><%= @shop.address%></p> 
    <p><%=  @shop.website %></p>
     <% if @shop.donuts != nil %>
      <p>It has these donuts: </p>
      <%@shop.donuts.each do |donut| %>
        <p>Name: <%= donut.name %></p>
        <p>Description: <%= donut.description %></p>
      <% end %>
    <% end %>
  </section>
</div> 
<div class="row">  
  <div class="col-md-4 col-md-offset-4 donut_shop_show" id= "map"></div>
</div> 
<section class="col-md-8 col-md-offset-2 donut_shop_show"> 
  <%= render "donuts/new" %>
</section>

app/views/donuts/_new.html.erb
<div class="row col-md-12">
  <div class="span4 well">
    <div class="new_donut">
      <h2>Add a new donut</h2>
      <%= form_for Donut.new, :html => {:class=>"form-horizontal center", :role=>"form"} do |f| %>
      <div class="form-group">
        <%= f.label :name, class:"control-label col-sm-2" %>
        <div class="col-sm-10">
          <%= f.text_field :name %>
        </div>   
      </div>
      <div class="form-group">
        <%= f.label :type_of_donut, class:"control-label col-sm-2" %>
        <div class="col-sm-10">
          <div class="checkbox">
            <%= f.radio_button :type_of_donut, 'Yeast', :checked => false %> Yeast 
            <%= f.radio_button :type_of_donut, 'Old Fashion/Cake', :checked => false %> Old Fashion/Cake 
            <%= f.radio_button :type_of_donut, 'Speciality', :checked => false %> Speciality
            <%= f.radio_button :type_of_donut, 'Glutton Free', :checked => false %> Glutton Free 
          </div>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :occasion, class:"control-label col-sm-2" %>
        <div class="col-sm-8">
          <%= f.radio_button :occasion , 'Splurge', :checked => false %> Splurge 
          <%= f.radio_button :occasion , 'Value', :checked => false %> Value
          <%= f.radio_button :occasion , 'Geographic Desirability', :checked => false %> Geographic Desirability </br>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :description, class:"control-label col-sm-3" %>
        <div class="col-sm-6">
          <%= f.text_area :description, spellcheck:"true" %>
        </div>
      </div>
      <div class="form-group donut_shop_select">
        <div class="col-sm-8">
          <%= collection_select(:donut, :donut_shop_id, DonutShop.all, :id, :name) %>
         OR <%= link_to "Add a new donut shop", new_donut_shop_form_path, remote: true %></br>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :picture, class:"control-label col-sm-2" %>
        <div class="col-sm-10">
          <%= f.hidden_field(:picture_cache) %>
          <%= f.file_field(:picture) %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-8">
          <%= submit_tag "Create a Donut" %>
         </div> 
      </div>
      <% end %>
    </div>
  </div>
</div> 

 

app/views/donuts/index.html.erb
<h2 class="title_page">Donuts<h2>
<div class="expanded row donut">
  <% @donuts.each do |donut| %>
    <section class="col-md-3 col-md-offset-2 donut">
      <div>
        <h4><%= link_to donut.name, donut_path(donut), id: donut.name  %></h4>
        <h5>From: <%= link_to donut.donut_shop.name %></h5> 
      </div>    
    </section>  
  <% end %>
</div>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <% if logged_in %>
      <%= render 'donuts/new' %>
    <% else %>
      <%= render partial: 'users/login_needed' %>
    <% end %>
  </div> 
</div>   

app/views/donuts/show.html.erb
<div class="row">
  <section class="col-md-8 col-md-offset-2 donut_show ">
    <h2 class="title">Each donut is different each day. </h2>
    <p>Name: <%= @donut.name %></p>
    <p><%= image_tag(@donut.picture_url(:thumb)) unless @donut.picture_url(:thumb).blank? %></p>
    <p>Description: <%= @donut.description %></p>
    <p>Donut Shop: <%= @donut.donut_shop.name %> </p>
  <section class="col-md-8 col-md-offset-2 ">
    <% if @ratings != nil %>
      <% @ratings.each do |r| %>
        <div class="center-block rating">
          <%= r.score %></br>
          <%= r.description %>
           - <%= User.find(r.user_id).first_name %>
        </div>
      <% end %>
    <% end %>
   </section> 
  </section> 
</div>  
<div class="row">  
  <section class="col-md-8 col-md-offset-2">
    <%= render "donut_ratings/new" %>
  </section>
</div>

app/views/users/_login_needed.html.erb
<div class="login_or_register">
  <h3>Please <%=link_to "log in", login_path %> or <%= link_to "create an account",  new_user_path %> to participate!!!!</h3>
</div>

app/views/users/_new.html.erb
<div class="row-fluid ">
  <div class="span4 well">
    <%= form_for @user, :html => {:class => "form-horizontal center"} do |f| %> 
      <div class="form-group">
        <%= f.label :first_name, class:"control-label col-sm-2" %>
        <div class="col-sm-6">
          <%= f.text_field :first_name, class:"form-control" %><br />
        </div>
      </div>
      <div class="form-group">
        <%= f.label :last_name, class:"control-label col-sm-2" %>
        <div class="col-sm-6">
          <%= f.text_field :last_name, class:"form-control" %><br />
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, class:"control-label col-sm-2" %>
        <div class="col-sm-6">
          <%= f.text_field :email, class:"form-control" %><br />
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password, class:"control-label col-sm-2" %>
        <div class="col-sm-6">
          <%= f.password_field :password, class:"form-control" %><br />
        </div>
      </div>
      <div class="form-group"> <br />
      <%= f.label :password_confirmation, class:"control-label col-sm-2" %>
        <div class="col-sm-6">
          <%= f.password_field :password_confirmation, class:"form-control" %><br />
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>


 

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="span4 well">
      <%= form_for @user, :html => {:class => "form-horizontal center"} do |f| %> 
        <div class="form-group">
          <%= f.label :first_name, class:"control-label col-sm-2" %>
          <div class="col-sm-6">
            <%= f.text_field :first_name, class:"form-control" %><br />
          </div>
        </div>
        <div class="form-group">
          <%= f.label :last_name, class:"control-label col-sm-2" %>
          <div class="col-sm-6">
            <%= f.text_field :last_name, class:"form-control" %><br />
          </div>
        </div>
        <div class="form-group">
          <%= f.label :email, class:"control-label col-sm-2" %>
          <div class="col-sm-6">
            <%= f.text_field :email, class:"form-control" %><br />
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password, class:"control-label col-sm-2" %>
          <div class="col-sm-6">
            <%= f.password_field :password, class:"form-control" %><br />
          </div>
        </div>
        <div class="form-group"> <br />
        <%= f.label :password_confirmation, class:"control-label col-sm-2" %>
          <div class="col-sm-6">
            <%= f.password_field :password_confirmation, class:"form-control" %><br />
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>


 

app/views/users/show.html.erb
<div class="user">
    <h2>Number of Donuts Rated: <%= @donuts_rated.count %></h2>
    <h2></h2>
    <%= render 'users/new' %>

</div>

app/views/welcome/about.html.erb
<section class="row">
  <div class="col-md-8 col-md-offset-2 about">
    <h2>About</h2>
    <p>I was bored and needed something to code and my friend had donuts on the mind. This is how all great things come to life.</p>
  </div>
</section>

app/views/welcome/index.html.erb
<div class ="row welcome">
  <h2 class="col-md-3 col-md-offset-1 welcome">Every donut is special.</h2> 
  <div class="col-md-5 col-md-offset-0">
    <img id="donut_pic" src="donut.jpg">
  </div>
</div>