config/routes.rb
Rails.application.routes.draw do

  root :to => 'welcome#index'
  get    'about'   => 'welcome#about'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :donuts do
    resources :donut_ratings
  end
  resources :donut_shops
  get 'new_donut_shop_form' => 'donut_shops#new_donut_shop_form'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :donuts, only: [:index, :create, :show, :update, :destroy]
      resources :donut_shops, only: [:index, :create, :show, :update, :destroy]
      resources :donut_ratings, only: [:index, :create, :show, :update, :destroy]
      resources :sessions, only: [:create]
    end
  end

end

app/models/donut.rb
class Donut < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  include ActiveModel::Serialization
  has_many :donut_ratings
  belongs_to :donut_shop
  accepts_nested_attributes_for :donut_shop

  validates :name, :description, :donut_shop_id, :presence => true
  validates :name, uniqueness: { scope: :donut_shop_id } 

end

app/models/donut_rating.rb
class DonutRating < ActiveRecord::Base
  validates :user_id, :donut_id, :score, :description, :donut_shop_id, :presence => true

  def self.average_rating(donut_id)
    ratings = where(donut_id: donut_id)
    sum(ratings) / ratings.length
  end

  private
  def self.sum(ratings)
    ratings.inject (0) {|sum, r| sum + r.score } 
  end
end

app/models/donut_shop.rb
class DonutShop < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  has_many :donut_ratings
  has_many :donuts

  validates :name, :description, :address, :phone, :website, presence: true
  validates :address, :phone, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many  :donut_ratings
  has_many :rated_donuts, through: :donut_ratings, foreign_key: :donut
  has_many :rated_donut_shops, through: :donut_ratings, foreign_key: :donut_shop
  validates :email, :first_name, :last_name, :password, :presence => true
  validates_confirmation_of :password, :message => "They need to match"

   before_create :generate_authentication_token

  private
  def generate_authentication_token
    loop do
      self.authentication_token = SecureRandom.base64(64)
      break unless User.find_by(authentication_token: authentication_token)
    end
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  protect_from_forgery with: :null_session

  before_action :destroy_session
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def destroy_session
    request.session_options[:skip] = true
  end


  def not_found
    return api_error(status: 404, errors: 'Sorry, the record was not found')
  end

 private
  def authenticate_user!
    user_email = params[:email]
    user = user_email && User.find_by(email: user_email)

    if user && ActiveSupport::SecurityUtils.secure_compare(user.authentication_token, params["token"])
      @current_user = user
    else
      return unauthenticated!
    end
  end

   def unauthenticated!
    response.headers['WWW-Authenticate'] = "Token realm=Application"
    render json: { error: 'Bad credentials' }, status: 401
  end
end

app/controllers/api/v1/donuts_controller.rb
class Api::V1::DonutsController < Api::V1::BaseController
  before_filter :authenticate_user!
  def show
    donut = Donut.find(params[:id])
    render(json: Api::V1::DonutSerializer.new(donut).to_json)
  end

   def index
    donuts = Donut.all
    render(json: donuts.each{|d| Api::V1::DonutSerializer.new(d).to_json})
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donut_ratings_controller.rb
require 'support/spec_test_helper'
class DonutRatingsController < ApplicationController

  def create
    @rating = DonutRating.new(rating_params)
    @rating.donut_id = params[:donut_id]
    @rating.user_id = session[:user_id]
    @donut = Donut.find(@rating.donut_id)
    @rating.donut_shop_id = @donut.donut_shop_id
    if @rating.valid?
      @rating.save
      redirect_to @donut
    else
      @errors = @rating.errors.full_messages
      render 'donut_shops/new'
    end
  end

  private

  def rating_params
    params.require(:donut_rating).permit( :score, :description)
  end


end

app/controllers/donut_shops_controller.rb
class DonutShopsController < ApplicationController


  def index
    @shops = DonutShop.all
  end

  def show
    @shop = DonutShop.find(params[:id])
    @donuts = Donut.find_by(:donut_shop_id => @shop.id)
  end

  def create
    @shop = DonutShop.new(shop_params)
    if @shop.save
      redirect_to @shop
    else
      @errors = @shop.errors.full_messages
      render 'donut_shops/new'
    end
  end

  def new_donut_shop_form
    respond_to do |format|
      format.js 
    end
  end


  private

  def shop_params
    params.require(:donut_shop).permit(:name, :description, :address, :phone, :website, :picture)
  end
  
end

app/controllers/donuts_controller.rb
class DonutsController < ApplicationController

  def new
    @shops = DonutShop.all
  end

  def create
    @donut = Donut.new(donut_params)
    if @donut.save
      render "donuts/show"
    else
      redirect_to root_path
    end
  end

  def show
    session[:donut_id] = params[:id]
    @donut = Donut.find(params[:id])
    @donut_shop = DonutShop.find(@donut.donut_shop_id)
    @ratings = DonutRating.where(donut_id: session[:donut_id]) 
    
  end

  def index
    @donuts = Donut.all
  end

  private

  def donut_params
    params.require(:donut).permit(:name, :description, :occasion, :type_of_donut, :donut_shop_id, :picture)
  end


 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create 
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to login_url, :notice => "Something went wrong, try again."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "You are logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def new 
    @user = User.new
  end
  
  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "You signed up!"
    else
      @errors = @user.errors.full_messages
      render "users/new"
    end 
  end

  def show
    @user = User.find(session[:user_id])
    @donuts_rated = DonutRating.where(user_id: session[:user_id])
  end

  def update
    @user = @user = User.find(session[:user_id])
    @user.update(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "You updated your profile."
    else
      @errors = @user.errors.full_messages
      render "users/new"
    end 

  end

  private
  
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/donut_shops_helper.rb
module DonutShopsHelper
  
end

app/helpers/form_helper.rb
module FormHelper
  def setup_donut(donut)
    donut.donut_shop ||= DonutShop.new
    donut
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in
    return true if session[:user_id] != nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if @errors%>
  <% @errors.each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<section class="footer">
  <h3><%= link_to "The Donut Database", donuts_path %></h3>
  <h2><%= link_to "About", about_path %></h2>
</section>  

app/views/layouts/_footer_google.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51171819-4', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <h1 id="name"><%= link_to "The Donut Database", donuts_path %></h1>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navigationbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navigationbar">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
    </nav>
  </div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
  <li> <%= link_to "Donuts", donuts_path %></li>
  <li> <%= link_to "Donut Shops", donut_shops_path %></li>
  <% if logged_in == true %>
    <li><%= link_to "Profile", user_path(session[:user_id])%></li>
    <li><%= link_to "Logout", logout_path, method: :delete %></li>
  <% else %>
    <li> <%= link_to "Login", login_path %></li>
    <li> <%= link_to "Register", new_user_path %></li>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Chicago Donut Club" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Chicago Donut Club" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages' %>
      <%= render 'layouts/errors' %>
      <%= yield %> 
      <%= render 'layouts/footer_google' %> 
      <%= render 'layouts/footer' %>
  </body>
</html>